### ISSUE TITLE
Ajouter une infobulle sur les étapes future

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/Unique#38]
## Description
Ajouter une infobulle sur les étapes future "Finish the previous steps"
## Trello
https://trello.com/c/Sh2jdsdR/52-clic-sur-bullet-grise-infobulle-faite-dabord-les-%C3%A9tapes-davant
## Planning Info
Time estimated 0.25
By @YoruNoHikage

**Comment by YoruNoHikage** [comment]
Already done by @Aldrian, translations needed though.
